import type { Metadata } from "next";
import { Press_Start_2P } from "next/font/google";
import "./globals.css";

import Link from "next/link";
import { HomeIcon, ClipboardDocumentCheckIcon, TrophyIcon } from "@heroicons/react/24/outline";

// Import da fonte pixelada
const pressStart2P = Press_Start_2P({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SakaTON",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${pressStart2P.className}
          bg-gray-900 
          text-white 
          antialiased 
          relative 
          min-h-screen
        `}
      >
        {/* Top Nav (SakaTON) */}
        <nav
          className="
            fixed top-0 left-0 w-full 
            bg-gray-800 border-b border-gray-700 
            px-4 py-3 z-50 
            flex items-center justify-center
          "
        >
          <h1
            className="
              absolute left-1/2 transform -translate-x-1/2
              text-base sm:text-lg md:text-xl font-bold
              text-transparent bg-clip-text 
              bg-gradient-to-r from-yellow-300 to-yellow-500
              tracking-widest
            "
          >
            SakaTON
          </h1>
        </nav>

        {/* Main Content with spacing for top & bottom nav */}
        <main className="pt-16 pb-16">{children}</main>

        {/* Bottom Navigation */}
        <nav className="fixed bottom-0 left-0 w-full bg-gray-800 border-t border-gray-700 p-3">
          <ul className="flex justify-around items-center">
            {[
              { href: "/", label: "Home", Icon: HomeIcon },
              { href: "/tasks", label: "Tasks", Icon: ClipboardDocumentCheckIcon },
              { href: "/ranking", label: "Ranking", Icon: TrophyIcon },
            ].map(({ href, label, Icon }) => (
              <li key={href}>
                <Link
                  href={href}
                  className="
                    flex flex-col items-center justify-center text-xs sm:text-sm 
                    p-2 rounded-lg bg-gray-700 hover:bg-yellow-500 transition-all 
                    duration-200 transform hover:scale-105 active:scale-95 shadow-md
                  "
                >
                  <Icon className="h-5 w-5 sm:h-6 sm:w-6" />
                  <span className="mt-1">{label}</span>
                </Link>
              </li>
            ))}
          </ul>
        </nav>
      </body>
    </html>
  );
}